server:
  port: 8090
spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
